from __future__ import annotations

from dataclasses import dataclass

PRESET_CATALOG_VERSION = 3

BANKING_CATEGORIES = frozenset({"central_bank", "bank_regulation", "banking", "fintech"})


@dataclass(frozen=True, slots=True)
class SourcePreset:
    id: str
    name: str
    url: str
    homepage: str
    category: str
    language: str
    terms: str
    default_enabled: bool = False


# The engine remains industry-neutral: these categories only help users choose
# feeds. Stable preset IDs preserve user changes across catalog upgrades.
SOURCE_PRESETS: tuple[SourcePreset, ...] = (
    SourcePreset(
        "preset-chinanews-scroll",
        "中新网 · 即时新闻",
        "https://www.chinanews.com.cn/rss/scroll-news.xml",
        "https://www.chinanews.com.cn/",
        "general",
        "zh",
        "https://www.chinanews.com.cn/common/footer/aboutus.shtml",
        True,
    ),
    SourcePreset(
        "preset-chinanews-world",
        "中新网 · 国际",
        "https://www.chinanews.com.cn/rss/world.xml",
        "https://www.chinanews.com.cn/gj/",
        "world",
        "zh",
        "https://www.chinanews.com.cn/common/footer/aboutus.shtml",
    ),
    SourcePreset(
        "preset-chinanews-finance",
        "中新网 · 财经",
        "https://www.chinanews.com.cn/rss/finance.xml",
        "https://www.chinanews.com.cn/cj/",
        "business",
        "zh",
        "https://www.chinanews.com.cn/common/footer/aboutus.shtml",
    ),
    SourcePreset(
        "preset-solidot",
        "Solidot",
        "https://www.solidot.org/index.rss",
        "https://www.solidot.org/",
        "technology",
        "zh",
        "https://www.solidot.org/",
    ),
    SourcePreset(
        "preset-cna-world",
        "中央社 · 国际",
        "https://feeds.feedburner.com/rsscna/intworld",
        "https://www.cna.com.tw/list/aopl.aspx",
        "world",
        "zh",
        "https://www.cna.com.tw/about/copyright.aspx",
    ),
    SourcePreset(
        "preset-cna-finance",
        "中央社 · 产经证券",
        "https://feeds.feedburner.com/rsscna/finance",
        "https://www.cna.com.tw/list/afe.aspx",
        "business",
        "zh",
        "https://www.cna.com.tw/about/copyright.aspx",
    ),
    SourcePreset(
        "preset-cna-technology",
        "中央社 · 科技",
        "https://feeds.feedburner.com/rsscna/technology",
        "https://www.cna.com.tw/list/ait.aspx",
        "technology",
        "zh",
        "https://www.cna.com.tw/about/copyright.aspx",
    ),
    SourcePreset(
        "preset-un-zh",
        "联合国新闻 · 中文",
        "https://news.un.org/feed/subscribe/zh/news/all/rss.xml",
        "https://news.un.org/zh/",
        "policy",
        "zh",
        "https://www.un.org/zh/about-us/copyright",
        True,
    ),
    SourcePreset(
        "preset-bbc-world",
        "BBC World",
        "https://feeds.bbci.co.uk/news/world/rss.xml",
        "https://www.bbc.com/news/world",
        "world",
        "en",
        "https://www.bbc.com/usingthebbc/terms",
    ),
    SourcePreset(
        "preset-bbc-business",
        "BBC Business",
        "https://feeds.bbci.co.uk/news/business/rss.xml",
        "https://www.bbc.com/news/business",
        "business",
        "en",
        "https://www.bbc.com/usingthebbc/terms",
    ),
    SourcePreset(
        "preset-guardian-world",
        "The Guardian · World",
        "https://www.theguardian.com/world/rss",
        "https://www.theguardian.com/world",
        "world",
        "en",
        "https://www.theguardian.com/help/terms-of-service",
    ),
    SourcePreset(
        "preset-guardian-business",
        "The Guardian · Business",
        "https://www.theguardian.com/uk/business/rss",
        "https://www.theguardian.com/uk/business",
        "business",
        "en",
        "https://www.theguardian.com/help/terms-of-service",
    ),
    SourcePreset(
        "preset-sciencedaily-top",
        "ScienceDaily · Top",
        "https://www.sciencedaily.com/rss/top.xml",
        "https://www.sciencedaily.com/",
        "science",
        "en",
        "https://www.sciencedaily.com/terms.htm",
    ),
    SourcePreset(
        "preset-nsf-news",
        "NSF News",
        "https://www.nsf.gov/rss/rss_www_news.xml",
        "https://www.nsf.gov/news/",
        "science",
        "en",
        "https://www.nsf.gov/policies/",
        True,
    ),
    SourcePreset(
        "preset-wto-news",
        "WTO News",
        "https://www.wto.org/library/rss/latest_news_e.xml",
        "https://www.wto.org/english/news_e/news_e.htm",
        "policy",
        "en",
        "https://www.wto.org/english/info_e/copyright_e.htm",
        True,
    ),
    SourcePreset(
        "preset-un-en",
        "UN News · English",
        "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
        "https://news.un.org/en/",
        "policy",
        "en",
        "https://www.un.org/en/about-us/copyright",
    ),
    # Catalog v2: these HTTPS RSS feeds were parsed with the same user agent and
    # response-size limits as the app on 2026-09-10.  They stay disabled when
    # merged into an existing installation, so an upgrade never broadens a
    # user's source scope without an explicit choice.
    SourcePreset(
        "preset-sec-press-releases",
        "SEC · Press Releases",
        "https://www.sec.gov/news/pressreleases.rss",
        "https://www.sec.gov/newsroom/press-releases",
        "policy",
        "en",
        "https://www.sec.gov/about/privacy-information",
    ),
    SourcePreset(
        "preset-sec-speeches-statements",
        "SEC · Speeches & Statements",
        "https://www.sec.gov/news/speeches-statements.rss",
        "https://www.sec.gov/newsroom/speeches-statements",
        "policy",
        "en",
        "https://www.sec.gov/about/privacy-information",
    ),
    SourcePreset(
        "preset-eu-environment-news",
        "European Commission · Environment News",
        "https://environment.ec.europa.eu/node/92/rss_en",
        "https://environment.ec.europa.eu/news_en",
        "policy",
        "en",
        "https://commission.europa.eu/legal-notice_en",
    ),
    SourcePreset(
        "preset-eu-trade-news",
        "European Commission · Trade News",
        "https://policy.trade.ec.europa.eu/node/2/rss_en",
        "https://policy.trade.ec.europa.eu/news_en",
        "policy",
        "en",
        "https://commission.europa.eu/legal-notice_en",
    ),
    SourcePreset(
        "preset-bis-media-releases",
        "BIS · Media Releases",
        "https://www.bis.org/doclist/all_pressrels.rss",
        "https://www.bis.org/media/news",
        "business",
        "en",
        "https://www.bis.org/about/terms-conditions",
    ),
    SourcePreset(
        "preset-nasa-news-releases",
        "NASA · News Releases",
        "https://www.nasa.gov/news-release/feed/",
        "https://www.nasa.gov/news-release/",
        "science",
        "en",
        "https://www.nasa.gov/privacy/",
    ),
    SourcePreset(
        "preset-nasa-technology",
        "NASA · Technology",
        "https://www.nasa.gov/technology/feed/",
        "https://www.nasa.gov/technology/",
        "technology",
        "en",
        "https://www.nasa.gov/privacy/",
    ),
    SourcePreset(
        "preset-techcrunch",
        "TechCrunch",
        "https://techcrunch.com/feed/",
        "https://techcrunch.com/",
        "technology",
        "en",
        "https://techcrunch.com/terms-of-service/",
    ),
)


# Catalog v3: public, publisher-operated banking and finance subscriptions.
# Reviewed feed endpoints and discovery evidence: docs/source-catalog-v3.json.
SOURCE_PRESETS += (
    SourcePreset(
        "preset-hkma-press-zh",
        "香港金管局 · 新闻稿",
        "https://www.hkma.gov.hk/chi/other-information/rss/rss_press-release.xml",
        "https://www.hkma.gov.hk/chi/",
        "central_bank",
        "zh",
        "https://www.hkma.gov.hk/chi/other-information/terms-and-conditions-of-use/",
    ),
    SourcePreset(
        "preset-hkma-circulars-zh",
        "香港金管局 · 银行通告",
        "https://www.hkma.gov.hk/chi/other-information/rss/rss_circulars.xml",
        "https://www.hkma.gov.hk/chi/",
        "bank_regulation",
        "zh",
        "https://www.hkma.gov.hk/chi/other-information/terms-and-conditions-of-use/",
    ),
    SourcePreset(
        "preset-hkma-insight-zh",
        "香港金管局 · 汇思",
        "https://www.hkma.gov.hk/chi/other-information/rss/rss_insight.xml",
        "https://www.hkma.gov.hk/chi/",
        "central_bank",
        "zh",
        "https://www.hkma.gov.hk/chi/other-information/terms-and-conditions-of-use/",
    ),
    SourcePreset(
        "preset-hk-sfc-news-zh",
        "香港证监会 · 新闻稿",
        "https://www.sfc.hk/TC/RSS-Feeds/Press-releases",
        "https://www.sfc.hk/TC/",
        "bank_regulation",
        "zh",
        "https://www.sfc.hk/en/Quick-links/Others/Hyperlink-policy",
    ),
    SourcePreset(
        "preset-hk-sfc-circulars-zh",
        "香港证监会 · 通函",
        "https://www.sfc.hk/TC/RSS-Feeds/Circulars",
        "https://www.sfc.hk/TC/",
        "bank_regulation",
        "zh",
        "https://www.sfc.hk/en/Quick-links/Others/Hyperlink-policy",
    ),
    SourcePreset(
        "preset-boj-news-en",
        "日本银行 · 最新发布",
        "https://www.boj.or.jp/en/rss/whatsnew.xml",
        "https://www.boj.or.jp/en/",
        "central_bank",
        "en",
        "https://www.boj.or.jp/en/about/abouthp.htm",
    ),
    SourcePreset(
        "preset-jfsa-news-en",
        "日本金融厅 · 监管动态",
        "https://www.fsa.go.jp/fsaEnNewsList_rss2.xml",
        "https://www.fsa.go.jp/en/",
        "bank_regulation",
        "en",
        "https://www.fsa.go.jp/en/rules/index.html",
    ),
    SourcePreset(
        "preset-rba-media",
        "澳大利亚储备银行 · 新闻发布",
        "https://www.rba.gov.au/rss/rss-cb-media-releases.xml",
        "https://www.rba.gov.au/",
        "central_bank",
        "en",
        "https://www.rba.gov.au/copyright/",
    ),
    SourcePreset(
        "preset-rba-speeches",
        "澳大利亚储备银行 · 演讲",
        "https://www.rba.gov.au/rss/rss-cb-speeches.xml",
        "https://www.rba.gov.au/",
        "central_bank",
        "en",
        "https://www.rba.gov.au/copyright/",
    ),
    SourcePreset(
        "preset-hkgov-finance-zh",
        "香港政府新闻网 · 财经",
        "https://www.news.gov.hk/tc/categories/finance/html/articlelist.rss.xml",
        "https://www.news.gov.hk/chi/",
        "banking",
        "zh",
        "https://www.news.gov.hk/eng/about/",
    ),
    SourcePreset(
        "preset-rthk-finance-zh",
        "香港电台 · 财经新闻",
        "https://rthk.hk/rthk/news/rss/c_expressnews_cfinance.xml",
        "https://news.rthk.hk/rthk/ch/",
        "banking",
        "zh",
        "https://www.rthk.hk/copyright/index.html",
    ),
    SourcePreset(
        "preset-fintech-singapore",
        "Fintech Singapore · 数字金融",
        "https://fintechnews.sg/feed/",
        "https://fintechnews.sg/",
        "fintech",
        "en",
        "https://fintechnews.sg/privacy-policy/",
    ),
    SourcePreset(
        "preset-fed-bank-regulation",
        "美联储 · 银行与消费者监管",
        "https://www.federalreserve.gov/feeds/press_bcreg.xml",
        "https://www.federalreserve.gov/supervisionreg.htm",
        "bank_regulation",
        "en",
        "https://www.federalreserve.gov/website-linking-policies.htm",
    ),
    SourcePreset(
        "preset-fed-enforcement",
        "美联储 · 执法行动",
        "https://www.federalreserve.gov/feeds/press_enforcement.xml",
        "https://www.federalreserve.gov/supervisionreg.htm",
        "bank_regulation",
        "en",
        "https://www.federalreserve.gov/website-linking-policies.htm",
    ),
    SourcePreset(
        "preset-fed-monetary-policy",
        "美联储 · 货币政策",
        "https://www.federalreserve.gov/feeds/press_monetary.xml",
        "https://www.federalreserve.gov/monetarypolicy.htm",
        "central_bank",
        "en",
        "https://www.federalreserve.gov/website-linking-policies.htm",
    ),
    SourcePreset(
        "preset-fed-supervision-letters",
        "美联储 · 监管函与手册",
        "https://www.federalreserve.gov/feeds/bankinginfo-rss.xml",
        "https://www.federalreserve.gov/supervisionreg.htm",
        "bank_regulation",
        "en",
        "https://www.federalreserve.gov/website-linking-policies.htm",
    ),
    SourcePreset(
        "preset-ecb-news",
        "欧洲央行 · 新闻与讲话",
        "https://www.ecb.europa.eu/rss/press.html",
        "https://www.ecb.europa.eu/",
        "central_bank",
        "en",
        "https://www.ecb.europa.eu/services/using-our-site/disclaimer/html/index.en.html",
    ),
    SourcePreset(
        "preset-ecb-bank-supervision",
        "欧洲央行 · 银行监管",
        "https://www.bankingsupervision.europa.eu/rss/press.html",
        "https://www.bankingsupervision.europa.eu/",
        "bank_regulation",
        "en",
        "https://www.bankingsupervision.europa.eu/services/disclaimer/html/index.en.html",
    ),
    SourcePreset(
        "preset-boe-news",
        "英格兰银行 · 新闻",
        "https://www.bankofengland.co.uk/rss/news",
        "https://www.bankofengland.co.uk/",
        "central_bank",
        "en",
        "https://www.bankofengland.co.uk/legal",
    ),
    SourcePreset(
        "preset-boe-prudential",
        "英格兰银行 · 审慎监管",
        "https://www.bankofengland.co.uk/rss/prudential-regulation-publications",
        "https://www.bankofengland.co.uk/prudential-regulation",
        "bank_regulation",
        "en",
        "https://www.bankofengland.co.uk/legal",
    ),
    SourcePreset(
        "preset-cfpb-newsroom",
        "美国CFPB · 消费金融保护",
        "https://www.consumerfinance.gov/about-us/newsroom/feed/",
        "https://www.consumerfinance.gov/about-us/newsroom/",
        "bank_regulation",
        "en",
        "https://www.consumerfinance.gov/privacy/website-privacy-policy/",
    ),
    SourcePreset(
        "preset-bis-research",
        "BIS · 金融与监管研究",
        "https://www.bis.org/doclist/bis_fsi_publs.rss",
        "https://www.bis.org/",
        "banking",
        "en",
        "https://www.bis.org/about/terms-conditions",
    ),
    SourcePreset(
        "preset-bis-central-bank-speeches",
        "BIS · 全球央行讲话",
        "https://www.bis.org/doclist/cbspeeches.rss",
        "https://www.bis.org/",
        "central_bank",
        "en",
        "https://www.bis.org/about/terms-conditions",
    ),
    SourcePreset(
        "preset-eba-news",
        "欧洲银行管理局 · 新闻",
        "https://www.eba.europa.eu/news-press/news/rss.xml",
        "https://www.eba.europa.eu/publications-and-media/press-releases",
        "bank_regulation",
        "en",
        "https://www.eba.europa.eu/find-out-about-us/legal-notice",
    ),
    SourcePreset(
        "preset-boc-press-releases",
        "加拿大央行 · 新闻稿",
        "https://www.bankofcanada.ca/content_type/press-releases/feed/",
        "https://www.bankofcanada.ca/",
        "central_bank",
        "en",
        "https://www.bankofcanada.ca/terms/",
    ),
    SourcePreset(
        "preset-boc-market-notices",
        "加拿大央行 · 市场通知",
        "https://www.bankofcanada.ca/content_type/notices/feed/",
        "https://www.bankofcanada.ca/",
        "central_bank",
        "en",
        "https://www.bankofcanada.ca/terms/",
    ),
)

SOURCE_PRESETS_BY_URL = {preset.url: preset for preset in SOURCE_PRESETS}
